#!/usr/bin/env python3
import sys,traceback,os
import src,curses
from src.c_Authenticator import c_Authenticator
from src.c_Shell import c_Shell
from src.c_TerminalUserInterface import c_termianlUserInterface



def main():
    try:
        auth = c_Authenticator()
        # Check if the current user is the file owner
        uI = c_termianlUserInterface()
        if os.getuid() == os.stat(__file__).st_uid:
            if os.geteuid() != 0:
                if "-a" in sys.argv:
                    auth.m_admin(uI)
                
        if auth.authentication:
            ins =["Authentication Succesful"]
            options =["Continue"]
            uI.m_terminalUserInterface(options,ins)
            c_Shell(uI)
        else:
            sys.exit(1)

    except Exception as e:
        curses.endwin()
        traceback.print_exc()
        sys.exit(1)



if __name__ == "__main__":
    main()
